[package]
name = "bonsai-mc-cli"
version = "0.1.0-dev"
edition = "2024"
description = "A complete minecraft modpack building cli tool"
license = "MIT"
repository = "https://github.com/elizabethlfransen/bonsai-cli"

[dependencies]
atomic_enum = "0.3.0"
clap = { version = "4.6.5", features = ["derive"] }
cliclack = "0.5.5"
console = "0.16.4"
miette = { version = "7.6.0", features = ["derive", "fancy"] }
owo-colors = { version = "4.3.0", features = ["supports-colors"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
strip-ansi-escapes = "0.2.1"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["full"] }

[[bin]]
name = "bonsai"
path = "src/main.rs"
